### ISSUE TITLE
No output generation - no error

### ISSUE THREAD

**Issue by Fipz** [underlines/awesome-marketing-datascience#1]
Thanks for sharing this guide. I followed it step-by-step on my windows 11 machine (RTX 3090). 

I cannot generate any put. see the console output here 

> `(base) C:\Users\admin\text-generation-webui>python server.py --model llama-13b-hf --load-in-4bit --no-stream
> Loading llama-13b-hf...
> Loading model ...
> Done.
> Loaded the model in 7.30 seconds.
> Running on local URL:  http://127.0.0.1:7860
> 
> To create a public link, set `share=True` in `launch()`.
> Output generated in 2.20 seconds (0.00 tokens/s, 0 tokens)
> Output generated in 0.04 seconds (0.00 tokens/s, 0 tokens)
> Output generated in 0.04 seconds (0.00 tokens/s, 0 tokens)`

any ideas what is happening? I can see that the model is loaded into the VRAM.

thanks in advance!

**Comment by underlines** [comment]
newer models shouldn't have this problem anymore. stale issue closed
