### ISSUE TITLE
new models : Samantha 

### ISSUE THREAD

**Issue by AmineDjeghri** [underlines/awesome-marketing-datascience#10]
- https://huggingface.co/TheBloke/Samantha-7B-GGML
- https://huggingface.co/TheBloke/Samantha-7B-GPTQ
- https://huggingface.co/TheBloke/samantha-13B-GPTQ
- https://huggingface.co/TheBloke/samantha-13B-GGML
- https://huggingface.co/TheBloke/samantha-33B-GPTQ
- https://huggingface.co/TheBloke/samantha-33B-GGML

**Comment by underlines** [comment]
added
