### ISSUE TITLE
Potentially invalid classnames?

### ISSUE THREAD

**Issue by IngwiePhoenix** [underlines/awesome-marketing-datascience#3]
Hello!

I am not very much a python guy, but since my recent experiments with AI, I have gotten more used to how it works.

After following your LLaMa tutorial, I kept getting the error that the `LLaMATokenizer` was not found. After a bit of investigating, I found this:

![image](https://user-images.githubusercontent.com/2893716/226145104-999248b0-43e4-4f9a-8b19-7797ce4fbbab.png)

So, perhaps the classnames are invalid? Anything I can do here?

Thanks and kind regards,
Ingwie

**Comment by underlines** [comment]
did you install transformers original or the `pip install git+https://github.com/zphang/transformers.git@llama_push` after uninstalling with `pip uninstall transfromers` ?

**Comment by underlines** [comment]
Tokenizer has been renamed back 2 months ago. Issue should be solved with newer models and newer codebases.
