### ISSUE TITLE
[WIN] quant_cuda-0.0.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by joyryder** [underlines/awesome-marketing-datascience#4]
I am on windows 10 pro 21H2 and cannot install prebuild GPTQ wheel with the command:
python -m pip install quant_cuda-0.0.0-cp310-cp310-win_amd64.whl
Using anaconda python version Python 3.9.16. Any help would be appreciated.

**Comment by mylahham** [comment]
try: pip install https://github.com/acpopescu/bitsandbytes/releases/download/v0.37.2-win.1/bitsandbytes-0.37.2-py3-none-any.whl

from: https://www.reddit.com/r/Oobabooga/comments/12eniem/bitsandbytes_now_for_windows_8bit_cuda_functions/

**Comment by underlines** [comment]
@joyryder rewrote the whole guide. issue should be solved
